# Generated by Django 6.0.3 on 2026-03-31 11:58

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True, help_text='Auto-generated summary')),
                ('author', models.CharField(blank=True, max_length=200)),
                ('source_url', models.URLField(blank=True)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='768-dimensional embedding vector for semantic search', null=True, size=768)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, help_text='Full-text search vector', null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('shares', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(blank=True, db_index=True, max_length=100)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Article tags for categorization')),
                ('language', models.CharField(db_index=True, default='en', max_length=10)),
            ],
            options={
                'db_table': 'articles',
                'ordering': ['-published_at'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='articles_search__3b8987_gin'), django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='articles_tags_fb0edb_gin'), models.Index(fields=['published_at', 'category'], name='articles_publish_843bbb_idx'), models.Index(fields=['created_at'], name='articles_created_82e966_idx'), models.Index(fields=['views', 'published_at'], name='articles_views_3f7d25_idx')],
            },
        ),
        migrations.CreateModel(
            name='ArticleView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_records', to='articles.article')),
            ],
            options={
                'db_table': 'article_views',
            },
        ),
    ]
