# Generated by Django 6.0.3 on 2026-03-31 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='articleview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='articleview',
            index=models.Index(fields=['timestamp', 'article'], name='article_vie_timesta_616bcd_idx'),
        ),
        migrations.AddIndex(
            model_name='articleview',
            index=models.Index(fields=['article', 'timestamp'], name='article_vie_article_689b78_idx'),
        ),
    ]
