# Generated by Django 6.0.3 on 2026-04-24 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_initial'),
        ('articles', '0002_multimodal_search'),
    ]

    operations = [
    ]
