# Generated by Django 6.0.3 on 2026-03-31 11:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('shares_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('read_time_avg', models.FloatField(help_text='Average read time in seconds', null=True)),
                ('bounce_rate', models.FloatField(help_text='Bounce rate percentage', null=True)),
                ('traffic_source', models.CharField(blank=True, max_length=100)),
                ('referrer_domain', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'article_metrics',
            },
        ),
        migrations.CreateModel(
            name='DailyArticleStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('total_shares', models.PositiveIntegerField(default=0)),
                ('total_comments', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('avg_read_time', models.FloatField(null=True)),
                ('avg_bounce_rate', models.FloatField(null=True)),
                ('views_rank', models.PositiveIntegerField(help_text='Daily ranking by views', null=True)),
                ('engagement_rank', models.PositiveIntegerField(help_text='Daily ranking by engagement', null=True)),
            ],
            options={
                'db_table': 'daily_article_stats',
            },
        ),
        migrations.CreateModel(
            name='TrendingTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(db_index=True, max_length=200)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('mention_count', models.PositiveIntegerField(default=0)),
                ('article_count', models.PositiveIntegerField(default=0)),
                ('total_engagement', models.PositiveIntegerField(default=0)),
                ('trend_score', models.FloatField(help_text='Calculated trend score')),
                ('velocity', models.FloatField(help_text='Rate of change in mentions')),
            ],
            options={
                'db_table': 'trending_topics',
            },
        ),
        migrations.CreateModel(
            name='UserEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('time_spent', models.PositiveIntegerField(help_text='Time spent reading in seconds')),
                ('scroll_depth', models.FloatField(help_text='Percentage of article scrolled')),
                ('came_from', models.URLField(blank=True)),
                ('went_to', models.URLField(blank=True)),
                ('device_type', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'user_engagement',
            },
        ),
    ]
