# Generated by Django 6.0.3 on 2026-03-31 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userengagement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='articlemetrics',
            index=models.Index(fields=['timestamp', 'article'], name='article_met_timesta_01c191_idx'),
        ),
        migrations.AddIndex(
            model_name='articlemetrics',
            index=models.Index(fields=['article', 'timestamp'], name='article_met_article_ef59ff_idx'),
        ),
        migrations.AddIndex(
            model_name='articlemetrics',
            index=models.Index(fields=['timestamp', 'traffic_source'], name='article_met_timesta_099449_idx'),
        ),
        migrations.AddConstraint(
            model_name='articlemetrics',
            constraint=models.UniqueConstraint(fields=('article', 'timestamp'), name='unique_article_timestamp'),
        ),
        migrations.AddIndex(
            model_name='dailyarticlestats',
            index=models.Index(fields=['date', 'total_views'], name='daily_artic_date_5616be_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyarticlestats',
            index=models.Index(fields=['date', 'views_rank'], name='daily_artic_date_4faafd_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyarticlestats',
            index=models.Index(fields=['article', 'date'], name='daily_artic_article_14b663_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyarticlestats',
            constraint=models.UniqueConstraint(fields=('article', 'date'), name='unique_article_date'),
        ),
        migrations.AddIndex(
            model_name='trendingtopic',
            index=models.Index(fields=['timestamp', 'trend_score'], name='trending_to_timesta_0cb9d0_idx'),
        ),
        migrations.AddIndex(
            model_name='trendingtopic',
            index=models.Index(fields=['topic', 'timestamp'], name='trending_to_topic_c90ae9_idx'),
        ),
        migrations.AddIndex(
            model_name='userengagement',
            index=models.Index(fields=['timestamp', 'article'], name='user_engage_timesta_1ba459_idx'),
        ),
        migrations.AddIndex(
            model_name='userengagement',
            index=models.Index(fields=['session_id', 'timestamp'], name='user_engage_session_bfe1af_idx'),
        ),
        migrations.AddIndex(
            model_name='userengagement',
            index=models.Index(fields=['user', 'timestamp'], name='user_engage_user_id_a34743_idx'),
        ),
    ]
